### ISSUE TITLE
Adding reset method

### ISSUE THREAD

**Issue by TomCat666** [8none1/idotmatrix#1]
Hello

First and foremost - thank you for this implementation. I was finally able to send GIFs to the device. My device does not work with the other python library/client that you mention in the readme - there it only works with upto 500 byte sized gifs. Their generation of header is unfortunately faulty. Could not debug it so I just used yours.
Everything is working fine, but after an hour or so the device gets problematic - it stops receiving data for some reason. Only thing I can do is to turn it off with long press on POWER and ON again and use the android APP, settings and RESET device option (which sends the DELETE command to it). Unfortunately this command is nowhere properly documented, the other python implementation has the Delete command implemented but it does not work (it doesn't generate a response from the device), it sends the following bytes (not hex) 👍 

17,0,2,1,12,0,1,2,3,4,5,6,7,8,9,10,11

If it would be possible to get this command working I could just send it every now and then to reset the device and it would be sort of a solution. Nothing else worked... the device stops working randomly unfortunetly. 
I don't know how to reverse engineer the APK to get this info or how would be best approach to do this?

**Comment by TomCat666** [comment]
"unzipped" the apk and found this sequence of bytes in the classes2.dex file (17,0,2,1,12,0,1,2,....) - tried adding more bytes that follow the sequence in the file, but it unfortunetly didn't help. There is no response being returned after.

**Comment by 8none1** [comment]
Curious.  Do I understand correctly:

 - You write a GIF to the device
 - The script ends and Bluetooth gets disconnected
 - Do nothing for an hour or so
 - And now you can't reconnect to the device and display a new image

And then you have to forcibly reset it via a command in the Android app?

I'll see if I can recreate this problem....

**Comment by TomCat666** [comment]
Thank you for a quick reply.

What I do is send a lot of GIF pictures/animations to the device - have around 1000 or so in my directory so in python I traverse the directory and send a random GIF to the device, then wait 10 seconds and send another and do this in an infinite loop.
It goes OK for a while then after an hour (sometimes before or later) the device just stays on the last gif picture (it could have colours corrupted though) but you can see the python script still sending the data to the device, just nothing actually happens on the display.
The only thing that helps is using the iDotmatrix APP, going into the settings (the gear icon) and issuing "Reset Device" command.
After I do that I can again start sending GIF's to the device.

**Comment by TomCat666** [comment]
Spent the day now trying to get the Blutooth logs on my android phone. I got the btsnoop_hci.log but cannot find ANY packets that would resemble what your python script is sending to the device for some reason. It is very interesting though :)

**Comment by 8none1** [comment]
It looks like there are two commands that are sent when resetting:

```text
24939	257.509	Master_0x6a4f2055	LE 1M	ATT	11	14688µs	0	0	False	7536		04000380			Sent Write Command, Handle: 0x0006 (Unknown: Unknown)
24941	257.524	Master_0x6a4f2055	LE 1M	ATT	12	14602µs	1	1	False	7537		0500048050			Sent Write Command, Handle: 0x0006 (Unknown: Unknown)
```

So it might be as simple as sending:

```text
04 00 03 80
05 00 04 80 50
```

Let me hack that in and try it....

**Comment by 8none1** [comment]
I added a reset command here:  https://github.com/8none1/idotmatrix/commit/1a08e1e9b82d78427ab1c896c24c2a7fb45bc2f0

See if that helps at all.

Thanks for trying this script out, and congratulations on making it work!  I'd forgotten quite how half-finished it was :D

**Comment by 8none1** [comment]
> Spent the day now trying to get the Blutooth logs on my android phone. I got the btsnoop_hci.log but cannot find ANY packets that would resemble what your python script is sending to the device for some reason. It is very interesting though :)

If you are interested in learning a bit more about reverse engineering BT LE devices I highly recommend getting hold of an [nRF52840 dongle](https://docs.nordicsemi.com/bundle/ug_nrf52840_dongle/page/UG/nrf52840_Dongle/intro.html) and flashing it with the sniffer software.

Full details here:  https://docs.nordicsemi.com/bundle/nrfutil_ble_sniffer_pdf/resource/nRF_Sniffer_BLE_UG_v4.0.0.pdf

It integrates in to Wireshark and you get this kind of view in to what's being sent to and from the device.  It's so much easier than using the Android debugging tools.

![image](https://github.com/user-attachments/assets/02e4d775-df6f-4a27-a8f4-42e93a60ac3a)

**Comment by TomCat666** [comment]
Thank you very much for all the help.

I am now trying out the reset method (currently have both commands in, it seems both are needed) - it is pretty much instant, it shows the rainbow screen when executed (same as the APP) so I think it might do the job.
I am applying the reset method after every 9 GIF's I am sending... will leave it running for the rest of the day and see if it helps.

Also thanx for the info about the dongle, definetly looks interesting and might come in handy for other stuff too. If only there were more hours in the day to work on everything that interests us :) 

Will keep you informed on how the reset works out.

**Comment by TomCat666** [comment]
It is a complete success. With reset applied every few GIF uploads it was going now for 7 hours without any problems. Thank you again for all the help.

**Comment by 8none1** [comment]
Glad to hear it!

![image](https://github.com/user-attachments/assets/b46e3ef5-46d2-4c90-b03b-d974d0b7ac0a)
